# Generated by Django 5.0.7 on 2024-07-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgcon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_at', models.DateTimeField(auto_now=True)),
                ('order_name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('bell_number', models.IntegerField()),
            ],
        ),
    ]
