# Generated by Django 5.0.7 on 2024-07-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgcon', '0002_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.AddField(
            model_name='menu',
            name='categories',
            field=models.ManyToManyField(blank=True, to='lgcon.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True),
        ),
    ]
